apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer
  ports:
    - protocol: "TCP"
      port: 9091


apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  ports:
    - protocol: "TCP"
      port: 9092

apiVersion: v1
kind: Service
metadata:
  name: resource-service
spec:
  selector:
    app: resource
  ports:
    - protocol: "TCP"
      port: 9090

apiVersion: v1
kind: Service
metadata:
  name: mysqldb-customer-service
spec:
  selector:
    app: mysqldb-customer
  ports:
     - port: 6003

apiVersion: v1
kind: Service
metadata:
  name: mysqldb-payment-service
spec:
  selector:
    app: mysqldb-payment
  ports:
     - port: 6004

apiVersion: v1
kind: Service
metadata:
  name: mysqldb-resource
spec:
  selector:
    app: mysqldb-resource
  ports:
     - port: 6002

apiVersion: v1
kind: Service
metadata:
  name: apigw-service
spec:
  selector:
    app: apigw
  ports:
     - port: 58081
       targetPort: 58081
       name: apigw
  type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
    name: metrics
spec:
    ports:
     - port: 58081
    selector:
      app: apigw


apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: apigw
  ports:
     - port: 9093
       targetPort: 9093
       name: prometheus
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: youmedia/youmedia:customer
          ports:
            - containerPort: 9091
          env:
            - name: MYSQL_HOST
              value: mysqldb-customer
            - name: DATASOURCE_URL
              value: jdbc:mysql://mysqldb-customer:6003/youmedia_db_customer
            - name: MYSQL_DATABASE
              value: youmedia_db_customer
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: youmedia
            - name: MYSQL_ROOT_PASSWORD
              value: youmedia

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: youmedia/youmedia:payment
          ports:
            - containerPort: 9092
          env:
            - name: MYSQL_HOST
              value: mysqldb-payment
            - name: DATASOURCE_URL
              value: jdbc:mysql://mysqldb-payment:6004/youmedia_db_payment
            - name: MYSQL_DATABASE
              value: youmedia_db_payment
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: youmedia
            - name: MYSQL_ROOT_PASSWORD
              value: youmedia

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource
spec:
  selector:
    matchLabels:
      app: resource
  template:
    metadata:
      labels:
        app: resource
    spec:
      containers:
        - name: resource
          image: youmedia/youmedia:resource
          ports:
            - containerPort: 9090
          env:
            - name: MYSQL_HOST
              value: mysqldb-resource
            - name: DATASOURCE_URL
              value: jdbc:mysql://mysqldb-resource:6002/youmedia_db_resource
            - name: MYSQL_DATABASE
              value: youmedia_db_resource
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: youmedia
            - name: MYSQL_ROOT_PASSWORD
              value: youmedia

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-customer
spec:
  selector:
    matchLabels:
      app: mysqldb-customer
  template:
    metadata:
      labels:
        app: mysqldb-customer
    spec:
      containers:
      - name: mysqldb-customer
        image: mysql:5.7
        ports:
        - containerPort: 6003
        env:
          - name: MYSQL_DATABASE
            value: youmedia_db_customer
          - name: MYSQL_USERNAME
            value: root
          - name: MYSQL_PASSWORD
            value: youmedia
          - name: MYSQL_ROOT_PASSWORD
            value: youmedia

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-payment
spec:
  selector:
    matchLabels:
      app: mysqldb-payment
  template:
    metadata:
      labels:
        app: mysqldb-payment
    spec:
      containers:
      - name: mysqldb-payment
        image: mysql:5.7
        ports:
        - containerPort: 6004
        env:
          - name: MYSQL_DATABASE
            value: youmedia_db_payment
          - name: MYSQL_USERNAME
            value: root
          - name: MYSQL_PASSWORD
            value: youmedia
          - name: MYSQL_ROOT_PASSWORD
            value: youmedia
            
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-resource
spec:
  selector:
    matchLabels:
      app: mysqldb-resource
  template:
    metadata:
      labels:
        app: mysqldb-resource
    spec:
      containers:
      - name: mysqldb-resource
        image: mysql:5.7
        ports:
        - containerPort: 6002
        env:
          - name: MYSQL_DATABASE
            value: youmedia_db_resource
          - name: MYSQL_USERNAME
            value: root
          - name: MYSQL_PASSWORD
            value: youmedia
          - name: MYSQL_ROOT_PASSWORD
            value: youmedia

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw
spec:
  selector:
    matchLabels:
      app: pigw
  template:
      metadata:
        labels:
          app: apigw
      spec:
        containers:
        - name: apigw
          image: youmedia/youmedia:apigw
          ports:
          - containerPort: 58081
          volumeMounts:
              - mountPath: /app/var 
                name: apigw-storage
        volumes:
        - name: apigw-storage
          hostPath:
              path: /storage
              type: DirectoryOrCreate

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
      metadata:
        labels:
          app: prometheus
      spec:
        containers:
        - name: prometheus
          image: prom/prometheus
          ports:
          - containerPort: 9093
          volumeMounts:
              - mountPath: /etc/prometheus/prometheus.yml
                name: prometheus-config
          #command: ["--config.file=/etc/prometheus/prometheus.yml"]
        volumes:
        - name: prometheus-config
          hostPath:
              path: /storage/Prometheus/prometheus.yml
              type: File